# Generated by Django 5.0 on 2024-01-31 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('image_path', models.CharField(max_length=1024, unique=True)),
                ('text', models.TextField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('content', models.JSONField(verbose_name='content')),
                ('status', models.CharField(choices=[('InProgress', 'In progress'), ('Complete', 'Complete'), ('Conflict', 'Conflict')], default='InProgress', max_length=32)),
                ('version', models.PositiveSmallIntegerField()),
                ('row_creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_update_timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.page', verbose_name='page_id')),
            ],
        ),
    ]
