# Generated by Django 5.0 on 2024-01-28 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('row_update_timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('row_creation_timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('content', models.JSONField(verbose_name='content')),
                ('status', models.CharField(choices=[('InProgress', 'In progress'), ('Complete', 'Complete'), ('Conflict', 'Conflict')], default='InProgress', max_length=32)),
                ('version', models.PositiveSmallIntegerField()),
                ('ocr_result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.ocrresult', verbose_name='ocr_result_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
        ),
    ]
