# Generated by Django 5.0 on 2024-03-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_alter_annotation_contents'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('volume_id', 'page_no'), name='UX_volume_id_page_no'),
        ),
    ]
