# Generated by Django 5.0 on 2024-03-24 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_page_ux_volume_id_page_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(max_length=250000)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='EntryPages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='page',
            name='UX_volume_id_page_no',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='page',
            name='text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='volume_id',
        ),
        migrations.AddField(
            model_name='annotation',
            name='text',
            field=models.TextField(max_length=250000, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='volume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotation.volume'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('volume', 'page_no'), name='UX_volume_id_page_no'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotation.entry'),
        ),
        migrations.AddField(
            model_name='entrypages',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.entry'),
        ),
        migrations.AddField(
            model_name='entrypages',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.page'),
        ),
        migrations.AddConstraint(
            model_name='entrypages',
            constraint=models.UniqueConstraint(fields=('entry', 'page'), name='UX_entry_id_page_id'),
        ),
    ]
