# Generated by Django 5.0.4 on 2024-04-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_alter_page_page_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryPages',
            new_name='EntryPage',
        ),
    ]
