# Generated by Django 5.0.4 on 2025-01-10 08:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_rename_entrypages_entrypage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'verbose_name': 'annotation', 'verbose_name_plural': 'annotations'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='entrypage',
            options={'verbose_name': 'page entry', 'verbose_name_plural': 'page entries'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'volume', 'verbose_name_plural': 'volumes'},
        ),
        migrations.AddField(
            model_name='annotation',
            name='text_length',
            field=models.IntegerField(default=0, verbose_name='text length'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='title_word',
            field=models.TextField(default='', max_length=100, verbose_name='title word'),
        ),
        migrations.AddField(
            model_name='entry',
            name='text_length',
            field=models.IntegerField(default=0, verbose_name='text length'),
        ),
        migrations.AddField(
            model_name='entry',
            name='title_word',
            field=models.TextField(default='', max_length=100, verbose_name='title word'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotation.entry', verbose_name='entry'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='row_creation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='row creation timestamp'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='row_update_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='row update timestamp'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='version',
            field=models.PositiveSmallIntegerField(verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='entrypage',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.entry', verbose_name='entry'),
        ),
        migrations.AlterField(
            model_name='entrypage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_path',
            field=models.CharField(max_length=1024, unique=True, verbose_name='image path'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_no',
            field=models.PositiveIntegerField(verbose_name='page number'),
        ),
        migrations.AlterField(
            model_name='page',
            name='volume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotation.volume', verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
    ]
