# Generated by Django 5.0.4 on 2025-01-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_alter_annotation_options_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='title_word_normalized',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='title_word_normalized',
            field=models.TextField(default='', max_length=100),
        ),
    ]
