# Generated by Django 5.0.4 on 2025-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0008_annotation_title_word_normalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='row_update_timestamp',
            field=models.DateTimeField(null=True, verbose_name='row update timestamp'),
        ),
    ]
