# Generated by Django 5.0.4 on 2025-05-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_alter_annotation_row_update_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(max_length=250, verbose_name='text')),
                ('is_approved', models.BooleanField(verbose_name='is_approved')),
            ],
            options={
                'verbose_name': 'reference',
                'verbose_name_plural': 'references',
            },
        ),
    ]
