# Generated by Django 5.0.4 on 2025-05-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='text',
            field=models.TextField(max_length=250, unique=True, verbose_name='text'),
        ),
    ]
