# Generated by Django 5.0.4 on 2025-05-05 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_alter_reference_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='row_creation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='row creation timestamp'),
        ),
        migrations.AddField(
            model_name='reference',
            name='row_update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='row update timestamp'),
        ),
    ]
