# Generated by Django 5.0.4 on 2025-05-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0012_reference_row_creation_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationInterval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
            ],
            options={
                'verbose_name': 'evaluation interval',
                'verbose_name_plural': 'evaluation intervals',
            },
        ),
    ]
