# Generated by Django 5.0.4 on 2026-03-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0013_evaluationinterval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'dictionary',
                'verbose_name_plural': 'dictionaries',
            },
        ),
        migrations.AddField(
            model_name='volume',
            name='dictionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.dictionary', verbose_name='dictionary'),
        ),
    ]
