# Generated by Django 5.0.4 on 2026-03-15 11:17

from django.db import migrations


def add_edtlr_dictionary(apps, schema_editor):
    """Add the eDTLR dictionary to the database."""
    Dictionary = apps.get_model('annotation', 'Dictionary')
    edtlr = Dictionary(name="eDTLR")
    edtlr.save()


def update_dictionary_for_all_volumes(apps, schema_editor):
    """Set the parent dictionary for all volumes from the database."""
    Dictionary = apps.get_model('annotation', 'Dictionary')
    edtlr = Dictionary.objects.first()
    Volume = apps.get_model('annotation', 'Volume')
    for volume in Volume.objects.all():
        volume.dictionary = edtlr
        volume.save()


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0014_dictionary_volume_dictionary'),
    ]

    operations = [
        migrations.RunPython(add_edtlr_dictionary),
        migrations.RunPython(update_dictionary_for_all_volumes)
    ]
