# Generated by Django 5.0.4 on 2026-03-15 11:17

from django.db import migrations

APP_NAME = 'annotation'
DICTIONARY_MODEL = 'Dictionary'
VOLUME_MODEL = 'Volume'
DICTIONARY_NAME = 'eDTLR'


def add_edtlr_dictionary(apps, schema_editor):
    """Add the eDTLR dictionary to the database."""
    Dictionary = apps.get_model(APP_NAME, DICTIONARY_MODEL)
    Dictionary.objects.get_or_create(name=DICTIONARY_NAME)


def rollback_add_edtlr_dictionary(apps, schema_editor):
    """Rollback the insertion of the eDTLR dictionary to the database."""
    Dictionary = apps.get_model(APP_NAME, DICTIONARY_MODEL)
    Dictionary.objects.filter(name=DICTIONARY_NAME).delete()


def update_dictionary_for_all_volumes(apps, schema_editor):
    """Set the parent dictionary for all volumes from the database."""
    Dictionary = apps.get_model(APP_NAME, DICTIONARY_MODEL)
    edtlr = Dictionary.objects.get(name=DICTIONARY_NAME)
    Volume = apps.get_model(APP_NAME, VOLUME_MODEL)
    Volume.objects.update(dictionary=edtlr)


def rollback_update_dictionary_for_all_volumes(apps, schema_editor):
    """Rollback setting of the parent dictionary for all volumes from the database."""
    Dictionary = apps.get_model(APP_NAME, DICTIONARY_MODEL)
    Volume = apps.get_model(APP_NAME, VOLUME_MODEL)
    try:
        edtlr = Dictionary.objects.get(name=DICTIONARY_NAME)
    except Dictionary.DoesNotExist:
        # Nothing to revert
        return
    Volume.objects.update(dictionary=None)


class Migration(migrations.Migration):

    dependencies = [
        (APP_NAME, '0014_dictionary_volume_dictionary'),
    ]

    operations = [
        migrations.RunPython(add_edtlr_dictionary,
                             reverse_code=rollback_add_edtlr_dictionary),
        migrations.RunPython(
            update_dictionary_for_all_volumes,
            reverse_code=rollback_update_dictionary_for_all_volumes)
    ]
