# Generated by Django 5.0.4 on 2026-03-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0015_add_default_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='dictionary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='annotation.dictionary', verbose_name='dictionary'),
        ),
    ]
