# Generated by Django 5.0.4 on 2026-03-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0016_alter_volume_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
