# Generated by Django 5.0.4 on 2026-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0017_dictionary_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='volume',
            constraint=models.UniqueConstraint(fields=('dictionary', 'name'), name='unique_volumes_per_dictionary'),
        ),
    ]
