# Generated by Django 5.0.4 on 2026-03-16 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0018_alter_volume_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='dictionary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='annotation.dictionary', verbose_name='dictionary'),
        ),
    ]
