# Generated by Django 5.0.4 on 2026-03-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0019_alter_volume_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotation.dictionary', verbose_name='dictionary'),
        ),
    ]
