name: Deploy eDTLR Annotator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup ssh authorization
      env:
        SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
        SSH_PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PUBLIC_KEY" | tr -d '\r' > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        echo SSH agent started
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
        ssh-keyscan ${{secrets.HOST}} >> ~/.ssh/known_hosts

    - name: Test SSH
      run: ssh -p ${{secrets.SSH_PORT}} ${{secrets.USERNAME}}@${{secrets.HOST}} echo "Hello World!"  
    - name: Cleanup
      run: rm -rf ~/.ssh
      
        
  
